/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { 
  Compass, BookOpen, Sparkles, X, ChevronRight, ChevronLeft, 
  Landmark, Shield, Anchor, ScrollText, Activity, HelpCircle, 
  Lightbulb, CheckCircle2, Play, Cpu, Keyboard
} from 'lucide-react';
import { audio } from '../utils/audio';

export interface GameGuideModalProps {
  isOpen: boolean;
  onClose: () => void;
  onNavigateTab: (tab: 'campaign' | 'grid' | 'port' | 'tech' | 'voxel') => void;
  onOpenEpigraphs: (termId?: string) => void;
  onOpenTrends: () => void;
}

interface TourStep {
  title: string;
  tamilTitle: string;
  icon: string;
  badge: string;
  tabKey?: 'campaign' | 'grid' | 'port' | 'tech' | 'voxel';
  description: string;
  keyPoints: string[];
  actionLabel?: string;
  actionType?: 'tab' | 'epigraph' | 'trend';
  actionTarget?: string;
}

const TOUR_STEPS: TourStep[] = [
  {
    title: "1. The Four Pillars of the Empire",
    tamilTitle: "நான்கு தூண்கள்",
    icon: "🏛️",
    badge: "Resource Economy",
    description: "Every Chola ruler balances 4 vital imperial resource pillars to sustain the kingdom's expansion:",
    keyPoints: [
      "🪙 Aruvam (Wealth): Generated by Nagapattinam trade fleets & market towns.",
      "👁️ Arivu (Knowledge): Generated by Palm Leaf Scribes (Olai Chuvadi) & Saraswathi Mahal Archives.",
      "🪷 Anbu (Devotion): Generated by Peruvudaiyar Temple consecration & cultural rituals.",
      "⚔️ Aalavan (Military): Trained to protect trade routes against pirates and guard granite quarries."
    ],
    actionLabel: "View 10-Day Trend Chart",
    actionType: "trend"
  },
  {
    title: "2. Nagara Grid City Planning",
    tamilTitle: "நகர அமைப்பு",
    icon: "🗺️",
    badge: "City Builder Tab",
    tabKey: "grid",
    description: "Layout agricultural fields, stone quarries, and market centers on an 8x8 isometric grid:",
    keyPoints: [
      "🌊 River Cauvery: Flows at the top row. Zone Ur paddy fields adjacent to water for double crop yield!",
      "💧 Eri Reservoirs: Dig reservoirs to extend water irrigation channels deep into dry land.",
      "⛏️ Granite Quarries: Assign idle workers to mine massive granite blocks for temple construction.",
      "🏛️ Nagaram Markets: Convert paddy crops into rich Aruvam gold coins."
    ],
    actionLabel: "Go to Nagara Grid",
    actionType: "tab",
    actionTarget: "grid"
  },
  {
    title: "3. Nagapattinam Maritime Fleet",
    tamilTitle: "சோழர் கடற்படை",
    icon: "⛵",
    badge: "Port Fleet Tab",
    tabKey: "port",
    description: "Rule the Indian Ocean by building merchant vessels and war armadas across maritime trade lanes:",
    keyPoints: [
      "🚢 Maritime Routes: Dispatch merchant fleets to Sri Lanka (Eelam), Srivijaya (Indonesia), and Guangzhou (China).",
      "🏴‍☠️ Navy Battles: Deploy Kadal Pira war galleys to escort fleets and vanquish pirate raiders.",
      "📦 Cargo Processing: Process incoming spices, silk, and gems to earn maximum Aruvam and rare relics."
    ],
    actionLabel: "Open Maritime Port",
    actionType: "tab",
    actionTarget: "port"
  },
  {
    title: "4. Palm Leaf Tech Archives",
    tamilTitle: "ஓலைச்சுவடி நுட்பங்கள்",
    icon: "📜",
    badge: "Tech Tree Tab",
    tabKey: "tech",
    description: "Spend Arivu knowledge points to unlock historical innovations written on palm leaves (*Olai Chuvadi*):",
    keyPoints: [
      "🏺 Kudavolai Ballot: Unlocks democratic village council elections to eliminate corruption.",
      "🌊 Cascade Irrigation: Engineering upgrades that protect crops during monsoon cyclones.",
      "🐘 Elephant Ramp Mechanics: Unlocks 4-mile inclined earthen ramps to haul 80-ton granite capstones."
    ],
    actionLabel: "Explore Tech Tree",
    actionType: "tab",
    actionTarget: "tech"
  },
  {
    title: "5. Thanjavur Great Temple Campaign",
    tamilTitle: "தஞ்சைப் பெருவுடையார்",
    icon: "🛕",
    badge: "Main Campaign Tab",
    tabKey: "campaign",
    description: "Your primary grand objective is to complete the 216-foot Brihadeeswarar Temple vimana tower across 4 historic campaign phases:",
    keyPoints: [
      "Phase I: Quarry 130,000 tons of granite rock from River Cauvery quarries.",
      "Phase II: Engineer the 4-mile earthen ramp and deploy war elephant haulage teams.",
      "Phase III: Neutralize foreign spies and secure the 80-ton monolithic golden Kumbam capstone.",
      "Phase IV: Host the grand consecration festival (Kumbhabhishekam) to achieve ultimate victory!"
    ],
    actionLabel: "View Campaign Objective",
    actionType: "tab",
    actionTarget: "campaign"
  },
  {
    title: "6. Epigraphical Records & 3D Voxel Studio",
    tamilTitle: "கல்வெட்டுத் தரவுத்தளம்",
    icon: "🗿",
    badge: "Bonus Tools",
    tabKey: "voxel",
    description: "Immerse yourself in authentic historical artifacts and 3D voxel sandbox modeling:",
    keyPoints: [
      "📜 Kalvettu Records: Click any gold dashed term in game to read actual temple wall stone inscriptions.",
      "🧊 MagicaVoxel 3D Studio: Build and customize custom Dravidian temple voxel blocks with 3D isometric rendering.",
      "⌨️ Keyboard Shortcuts: Use keys [1-5] to jump between views, [?] for Guide, [E] for Epigraphs!"
    ],
    actionLabel: "Inspect Epigraphs",
    actionType: "epigraph",
    actionTarget: "meikirthi"
  }
];

export default function GameGuideModal({
  isOpen,
  onClose,
  onNavigateTab,
  onOpenEpigraphs,
  onOpenTrends
}: GameGuideModalProps) {
  const [currentStepIdx, setCurrentStepIdx] = useState<number>(0);
  const [activeGuideTab, setActiveGuideTab] = useState<'walkthrough' | 'shortcuts' | 'faq'>('walkthrough');

  if (!isOpen) return null;

  const currentStep = TOUR_STEPS[currentStepIdx];

  const handleNext = () => {
    if (currentStepIdx < TOUR_STEPS.length - 1) {
      audio.playYazh(480);
      setCurrentStepIdx(prev => prev + 1);
    }
  };

  const handlePrev = () => {
    if (currentStepIdx > 0) {
      audio.playYazh(380);
      setCurrentStepIdx(prev => prev - 1);
    }
  };

  const handleStepAction = (step: TourStep) => {
    audio.playBell();
    if (step.actionType === 'tab' && step.actionTarget) {
      onNavigateTab(step.actionTarget as any);
      onClose();
    } else if (step.actionType === 'epigraph') {
      onOpenEpigraphs(step.actionTarget || 'meikirthi');
      onClose();
    } else if (step.actionType === 'trend') {
      onOpenTrends();
      onClose();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fade-in">
      
      {/* Modal Card Container */}
      <div 
        id="game-guide-modal"
        className="relative w-full max-w-4xl bg-[#1C1713] rounded-2xl border-2 border-[#D2691E]/60 shadow-2xl flex flex-col overflow-hidden text-[#F4EFE6]"
      >
        
        {/* Header Bar */}
        <div className="bg-[#2D241E] px-6 py-4 border-b border-[#D2691E]/30 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-[#D2691E]/20 border border-[#D2691E]/50 flex items-center justify-center text-[#D4AF37]">
              <Compass className="w-6 h-6 animate-spin-slow" />
            </div>
            <div>
              <div className="text-[10px] font-mono uppercase tracking-widest text-[#D4AF37] flex items-center gap-1.5">
                <Sparkles className="w-3 h-3 text-[#D2691E]" /> Royal Imperial Academy (சோழர் வழிகாட்டி)
              </div>
              <h2 className="text-xl font-serif font-bold text-[#F4EFE6]">
                Chola Empire Guide & Interactive Walkthrough
              </h2>
            </div>
          </div>

          <button
            onClick={() => {
              audio.playDrum(false);
              onClose();
            }}
            className="p-2 rounded-lg bg-[#1C1713] hover:bg-stone-800 text-stone-400 hover:text-white transition cursor-pointer border border-[#D2691E]/20"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Navigation Mode Bar */}
        <div className="bg-[#241D18] px-6 py-2.5 border-b border-[#D2691E]/20 flex justify-between items-center text-xs font-mono">
          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                audio.playYazh(320);
                setActiveGuideTab('walkthrough');
              }}
              className={`px-3 py-1.5 rounded-md transition font-bold cursor-pointer flex items-center gap-1.5 ${
                activeGuideTab === 'walkthrough'
                  ? 'bg-[#D2691E] text-black shadow'
                  : 'bg-[#1C1713] text-stone-300 hover:bg-[#3D3028] border border-[#D2691E]/20'
              }`}
            >
              <Play className="w-3.5 h-3.5" /> Step-by-Step Tour ({currentStepIdx + 1}/{TOUR_STEPS.length})
            </button>

            <button
              onClick={() => {
                audio.playYazh(380);
                setActiveGuideTab('shortcuts');
              }}
              className={`px-3 py-1.5 rounded-md transition font-bold cursor-pointer flex items-center gap-1.5 ${
                activeGuideTab === 'shortcuts'
                  ? 'bg-[#D2691E] text-black shadow'
                  : 'bg-[#1C1713] text-stone-300 hover:bg-[#3D3028] border border-[#D2691E]/20'
              }`}
            >
              <Keyboard className="w-3.5 h-3.5" /> Keyboard Controls
            </button>

            <button
              onClick={() => {
                audio.playYazh(420);
                setActiveGuideTab('faq');
              }}
              className={`px-3 py-1.5 rounded-md transition font-bold cursor-pointer flex items-center gap-1.5 ${
                activeGuideTab === 'faq'
                  ? 'bg-[#D2691E] text-black shadow'
                  : 'bg-[#1C1713] text-stone-300 hover:bg-[#3D3028] border border-[#D2691E]/20'
              }`}
            >
              <HelpCircle className="w-3.5 h-3.5" /> Strategy FAQ
            </button>
          </div>

          <span className="hidden md:inline text-[10px] text-[#D4AF37]">
            Press <kbd className="px-1 py-0.5 bg-black rounded border border-stone-700 font-mono">?</kbd> or <kbd className="px-1 py-0.5 bg-black rounded border border-stone-700 font-mono">H</kbd> anytime
          </span>
        </div>

        {/* Main Content Area */}
        <div className="p-6 h-[420px] overflow-y-auto space-y-6">
          
          {activeGuideTab === 'walkthrough' && (
            <div className="space-y-5 animate-fade-in">
              
              {/* Step Progress Bullets */}
              <div className="flex items-center justify-between gap-2 overflow-x-auto pb-2 border-b border-[#D2691E]/20">
                {TOUR_STEPS.map((s, idx) => (
                  <button
                    key={idx}
                    onClick={() => {
                      audio.playYazh(300 + idx * 40);
                      setCurrentStepIdx(idx);
                    }}
                    className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-mono transition cursor-pointer whitespace-nowrap ${
                      idx === currentStepIdx
                        ? 'bg-[#D4AF37] text-black font-bold ring-2 ring-[#D2691E]'
                        : idx < currentStepIdx
                        ? 'bg-emerald-950 text-emerald-400 border border-emerald-800'
                        : 'bg-[#241D18] text-stone-400 border border-[#D2691E]/20'
                    }`}
                  >
                    <span>{s.icon}</span>
                    <span>Step {idx + 1}</span>
                  </button>
                ))}
              </div>

              {/* Step Detail Card */}
              <div className="stone-slab-card p-6 rounded-xl space-y-4 border border-[#D2691E]/40 relative overflow-hidden">
                <div className="flex items-center justify-between">
                  <span className="px-3 py-1 rounded-full bg-[#D2691E]/20 text-[#D4AF37] border border-[#D2691E]/40 text-xs font-mono font-bold uppercase tracking-wider">
                    {currentStep.badge}
                  </span>
                  <span className="text-3xl select-none">{currentStep.icon}</span>
                </div>

                <div>
                  <h3 className="text-xl font-serif font-bold text-amber-200 flex items-baseline gap-2">
                    <span>{currentStep.title}</span>
                    <span className="text-sm font-mono text-[#D4AF37]">({currentStep.tamilTitle})</span>
                  </h3>
                  <p className="text-xs font-mono text-stone-300 mt-2 leading-relaxed">
                    {currentStep.description}
                  </p>
                </div>

                {/* Key Points Bullet List */}
                <div className="bg-[#181310] p-4 rounded-lg border border-[#D2691E]/30 space-y-2">
                  <span className="text-[11px] font-mono text-[#D4AF37] uppercase tracking-wider font-bold block">
                    Core Mechanics & Tips:
                  </span>
                  <ul className="space-y-1.5 text-xs text-stone-200 font-mono">
                    {currentStep.keyPoints.map((pt, i) => (
                      <li key={i} className="flex items-start gap-2">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Action Trigger Button */}
                {currentStep.actionLabel && (
                  <div className="pt-2 flex justify-end">
                    <button
                      onClick={() => handleStepAction(currentStep)}
                      className="px-4 py-2 rounded-lg bg-[#D2691E] hover:bg-[#B85B17] text-black font-mono font-bold text-xs flex items-center gap-2 shadow-lg transition cursor-pointer hover:scale-105 active:scale-95"
                    >
                      <Sparkles className="w-4 h-4" />
                      <span>{currentStep.actionLabel}</span>
                      <ChevronRight className="w-4 h-4" />
                    </button>
                  </div>
                )}

              </div>

            </div>
          )}

          {/* Keyboard Controls Tab */}
          {activeGuideTab === 'shortcuts' && (
            <div className="space-y-4 animate-fade-in">
              <div className="text-xs font-mono text-stone-300">
                Use instant hotkeys to switch tabs and open analytical dialogs without moving your cursor:
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                
                <div className="bg-[#241D18] p-3.5 rounded-lg border border-[#D2691E]/30 flex items-center justify-between">
                  <span className="text-xs font-mono text-stone-200">Main Campaign View</span>
                  <kbd className="px-2.5 py-1 bg-black text-[#D4AF37] font-mono font-bold rounded border border-[#D2691E]">1</kbd>
                </div>

                <div className="bg-[#241D18] p-3.5 rounded-lg border border-[#D2691E]/30 flex items-center justify-between">
                  <span className="text-xs font-mono text-stone-200">Nagara City Grid Builder</span>
                  <kbd className="px-2.5 py-1 bg-black text-[#D4AF37] font-mono font-bold rounded border border-[#D2691E]">2</kbd>
                </div>

                <div className="bg-[#241D18] p-3.5 rounded-lg border border-[#D2691E]/30 flex items-center justify-between">
                  <span className="text-xs font-mono text-stone-200">Nagapattinam Port Fleet</span>
                  <kbd className="px-2.5 py-1 bg-black text-[#D4AF37] font-mono font-bold rounded border border-[#D2691E]">3</kbd>
                </div>

                <div className="bg-[#241D18] p-3.5 rounded-lg border border-[#D2691E]/30 flex items-center justify-between">
                  <span className="text-xs font-mono text-stone-200">Palm Leaf Tech Tree</span>
                  <kbd className="px-2.5 py-1 bg-black text-[#D4AF37] font-mono font-bold rounded border border-[#D2691E]">4</kbd>
                </div>

                <div className="bg-[#241D18] p-3.5 rounded-lg border border-[#D2691E]/30 flex items-center justify-between">
                  <span className="text-xs font-mono text-stone-200">MagicaVoxel 3D Studio</span>
                  <kbd className="px-2.5 py-1 bg-black text-[#D4AF37] font-mono font-bold rounded border border-[#D2691E]">5</kbd>
                </div>

                <div className="bg-[#241D18] p-3.5 rounded-lg border border-[#D2691E]/30 flex items-center justify-between">
                  <span className="text-xs font-mono text-stone-200">Epigraphical Database</span>
                  <kbd className="px-2.5 py-1 bg-black text-[#D4AF37] font-mono font-bold rounded border border-[#D2691E]">E</kbd>
                </div>

                <div className="bg-[#241D18] p-3.5 rounded-lg border border-[#D2691E]/30 flex items-center justify-between col-span-1 md:col-span-2">
                  <span className="text-xs font-mono text-stone-200">Toggle Game Guide / Walkthrough</span>
                  <kbd className="px-2.5 py-1 bg-black text-[#D4AF37] font-mono font-bold rounded border border-[#D2691E]">? or H</kbd>
                </div>

              </div>
            </div>
          )}

          {/* Strategy FAQ Tab */}
          {activeGuideTab === 'faq' && (
            <div className="space-y-4 animate-fade-in text-xs font-mono">
              
              <div className="bg-[#241D18] p-4 rounded-lg border border-[#D2691E]/30 space-y-1.5">
                <span className="text-[#D4AF37] font-bold block flex items-center gap-1.5">
                  <Lightbulb className="w-4 h-4 text-[#D2691E]" /> How do I complete the Great Temple Consecration?
                </span>
                <p className="text-stone-300 leading-relaxed">
                  Go to the <strong>Campaign Tab (1)</strong>. Advance through Phase I (Quarry 100 Granite), Phase II (Build Elephant Ramp with 200 Aruvam + 50 Arivu), Phase III (Catch Spies with 50 Aalavan), and Phase IV (Consecrate Brihadeeswarar with 300 Anbu)!
                </p>
              </div>

              <div className="bg-[#241D18] p-4 rounded-lg border border-[#D2691E]/30 space-y-1.5">
                <span className="text-[#D4AF37] font-bold block flex items-center gap-1.5">
                  <Lightbulb className="w-4 h-4 text-[#D2691E]" /> Why are my Ur Paddy fields not producing enough grain?
                </span>
                <p className="text-stone-300 leading-relaxed">
                  Paddy fields yield 2x crops when adjacent to water! Dig an <strong>Eri Reservoir</strong> next to dry fields or zone fields directly beside the top River Cauvery line.
                </p>
              </div>

              <div className="bg-[#241D18] p-4 rounded-lg border border-[#D2691E]/30 space-y-1.5">
                <span className="text-[#D4AF37] font-bold block flex items-center gap-1.5">
                  <Lightbulb className="w-4 h-4 text-[#D2691E]" /> How do I get more Idle Workers?
                </span>
                <p className="text-stone-300 leading-relaxed">
                  Idle workers increase as your population grows through high Anbu (Devotion) and unlocked technologies in the Palm Leaf Tech Tree.
                </p>
              </div>

            </div>
          )}

        </div>

        {/* Footer Navigation Bar */}
        <div className="bg-[#2D241E] px-6 py-3 border-t border-[#D2691E]/30 flex items-center justify-between">
          <button
            disabled={currentStepIdx === 0}
            onClick={handlePrev}
            className={`px-3.5 py-1.5 rounded-lg border text-xs font-mono font-bold flex items-center gap-1.5 transition ${
              currentStepIdx === 0
                ? 'opacity-30 border-stone-700 text-stone-500 cursor-not-allowed'
                : 'border-[#D2691E]/40 bg-[#1C1713] text-stone-200 hover:bg-[#3D3028] cursor-pointer'
            }`}
          >
            <ChevronLeft className="w-4 h-4" /> Previous Step
          </button>

          <span className="text-xs font-mono text-[#D4AF37]">
            Step {currentStepIdx + 1} of {TOUR_STEPS.length}
          </span>

          <button
            disabled={currentStepIdx === TOUR_STEPS.length - 1}
            onClick={handleNext}
            className={`px-3.5 py-1.5 rounded-lg border text-xs font-mono font-bold flex items-center gap-1.5 transition ${
              currentStepIdx === TOUR_STEPS.length - 1
                ? 'opacity-30 border-stone-700 text-stone-500 cursor-not-allowed'
                : 'border-[#D2691E] bg-[#D2691E] text-black hover:bg-[#B85B17] cursor-pointer'
            }`}
          >
            Next Step <ChevronRight className="w-4 h-4" />
          </button>
        </div>

      </div>

    </div>
  );
}
